/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.*;

/**
 *
 * @author mirji507
 */
public class MainMenu extends javax.swing.JFrame {
    ProductDAO dao;

   public MainMenu(ProductDAO dao) {
       initComponents();
       setLocationRelativeTo(null);
       this.setResizable(false);
       this.dao = dao;
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      productAdministrationLabel = new javax.swing.JLabel();
      btnAddNew = new javax.swing.JButton();
      btnView = new javax.swing.JButton();
      btnExit = new javax.swing.JButton();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

      productAdministrationLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
      productAdministrationLabel.setText("Product Administration");
      productAdministrationLabel.setName("productAdministrationLabel"); // NOI18N

      btnAddNew.setText("Add a New Product");
      btnAddNew.setName("btnAddNew"); // NOI18N
      btnAddNew.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnAddNewActionPerformed(evt);
         }
      });

      btnView.setText("View Product");
      btnView.setName("btnView"); // NOI18N
      btnView.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnViewActionPerformed(evt);
         }
      });

      btnExit.setText("Exit");
      btnExit.setName("btnExit"); // NOI18N
      btnExit.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnExitActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGap(27, 27, 27)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addComponent(btnAddNew, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                  .addComponent(productAdministrationLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addComponent(btnView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addContainerGap(29, Short.MAX_VALUE))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(productAdministrationLabel)
            .addGap(20, 20, 20)
            .addComponent(btnAddNew)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btnView)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btnExit)
            .addContainerGap(25, Short.MAX_VALUE))
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
      ProductReportDialog dialog = new ProductReportDialog(this, true, dao);
      dialog.setLocationRelativeTo(this);
      dialog.setVisible(true);
   }//GEN-LAST:event_btnViewActionPerformed

   private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
      System.exit(0);
   }//GEN-LAST:event_btnExitActionPerformed

   private void btnAddNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewActionPerformed
      //create the ProductEditor dialog
      ProductDialog p = new ProductDialog(this,true, dao);
      //set the location of the dialog to be centred on the main menu frame
      p.setLocationRelativeTo(this);
      p.setVisible(true);
   }//GEN-LAST:event_btnAddNewActionPerformed

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton btnAddNew;
   private javax.swing.JButton btnExit;
   private javax.swing.JButton btnView;
   private javax.swing.JLabel productAdministrationLabel;
   // End of variables declaration//GEN-END:variables
}
